providers:
  kubernetesIngress:
    publishedService:
      enabled: true     #if you want to use with kubernetes ingress, set it to true.
  kubernetesGateway:
    enabled: true

gateway:
  namespacePolicy: All

ingressRoute:
  dashboard:
    enabled: true
    entryPoints:
    - web
    - websecure

service:
  enabled: true
  spec:
    externalTrafficPolicy: Local
  annotations:
    service.beta.kubernetes.io/metal-lb: "true"
    metallb.universe.tf/address-pool: public-pool # Optional: If using MetalLB
  type: LoadBalancer # Change to LoadBalancer if using MetalLB
  ports:
    web:
      port: 80
      targetPort: 80
    websecure:
      port: 443
      targetPort: 443

# Additional configuration for dashboard access
dashboard:
  enabled: true
  ingress:
    enabled: true
    path: /c/
    pathType: Prefix
    annotations:
      kubernetes.io/ingress.class: traefik
    hosts:
    - host: "*.private.antoniocaccamo.work" #traefik.example.com  # Change to your desired host
      paths:
      - /