# Ip advertisement yaml configuration file

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: public-l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - public-pool