apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-address-pool
  namespace: metallb-system
spec:
  addresses:
# - 192.168.1.240 - 192.168.1.247  # microk8s
  - 192.168.1.248 - 192.168.1.253  # k3s
  autoAssign: true